name: amarcdn_s4
description: Flutter sdk for AmarCDN s4(Storage Service).
version: 0.0.1
homepage: https://github.com/amarcdn/amarcdn_s4_flutter_sdk

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: